image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-schedule-microservice:
  stage: build
  script:
    gradle schedule-microservice:assemble schedule-microservice:testClasses

checkStyle-schedule-microservice:
  stage: staticAnalysis
  script:
    gradle schedule-microservice:checkstyleMain schedule-microservice:checkStyleTest
  allow_failure: true


PMD-schedule-microservice:
  stage: staticAnalysis
  script:
    gradle schedule-microservice:pmdMain
  allow_failure: true

test-schedule-microservice:
  stage: test
  script:
    - gradle schedule-microservice:test schedule-microservice:jacocoTestReport
    - cat schedule-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
