image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-resources-microservice:
  stage: build
  script:
    gradle resources-microservice:assemble resources-microservice:testClasses

checkStyle-resources-microservice:
  stage: staticAnalysis
  script:
    gradle resources-microservice:checkstyleMain resources-microservice:checkStyleTest
  allow_failure: true


PMD-resources-microservice:
  stage: staticAnalysis
  script:
    gradle resources-microservice:pmdMain
  allow_failure: true

test-resources-microservice:
  stage: test
  script:
    - gradle resources-microservice:test resources-microservice:jacocoTestReport
    - cat resources-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
